import { getAIClient } from "@/ai";
import { NextRequest, NextResponse } from "next/server";

import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { slugify_with_underscores } from "@/lib/helpers";
import { interviewModeBodySchema } from "@/app/schema/interview-mode.schema";



export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const validationResult = interviewModeBodySchema.safeParse(body);

    if (!validationResult.success) {
      return NextResponse.json(
        {
          success: false,
          error: "Invalid request body",
          issues: validationResult.error.flatten().fieldErrors,
        },
        { status: 400 },
      );
    }

    const {
      interviewerVoice,
      intervieweeVoice,
      interviewerInput,
      intervieweeInput,
      fileName,
      interviewerInstruction,
      intervieweeInstruction,
    } = validationResult.data;

    // get AI client
    const aiClient = getAIClient();

    // Generate interviewer audio
    const interviewerAudioResponse = await aiClient.audio.speech.create({
      model: process.env.OPENAI_TTS_MODEL || "gpt-4o-mini-tts",
      voice: interviewerVoice,
      input: interviewerInput,
      instructions: interviewerInstruction,
      response_format: "mp3",
    });

    const interviewerAudioBuffer = Buffer.from(
      await interviewerAudioResponse.arrayBuffer(),
    );

    // Generate interviewee audio
    const intervieweeAudioResponse = await aiClient.audio.speech.create({
      model: process.env.OPENAI_TTS_MODEL || "gpt-4o-mini-tts",
      voice: intervieweeVoice,
      input: intervieweeInput,
      instructions: intervieweeInstruction,
      response_format: "mp3",
    });

    const intervieweeAudioBuffer = Buffer.from(
      await intervieweeAudioResponse.arrayBuffer(),
    );

    // Merge both MP3 buffers into a single downloadable MP3 file.
    // This works for a first local test because both files are generated by the same model and format.
    const mergedAudioBuffer = Buffer.concat([
      interviewerAudioBuffer,
      intervieweeAudioBuffer,
    ]);

    const outputDir = path.join(process.cwd(), "public", "generated");
    await mkdir(outputDir, { recursive: true });

    const baseName = fileName && fileName.length > 0
      ? fileName
      : interviewerInput;

    const safeFileName = slugify_with_underscores(baseName).slice(0, 120);
    const finalFileName = `${safeFileName}.mp3`;

    const filePath = path.join(outputDir, finalFileName);

    await writeFile(filePath, mergedAudioBuffer);

    const downloadLink = `/generated/${finalFileName}`;

    return NextResponse.json({
      success: true,
      message: "Audio generated successfully",
      data: {
        downloadLink,
      },
    });

  } catch (error) {
    console.error("POST /api/audio/interview-mode error:", error);
    return NextResponse.json(
      {
        success: false,
        error: `Unexpected error occurred while creating new audio`,
      },
      { status: 500 },
    );
  }
}
