import { getAIClient } from "@/ai";
import { Voice } from "@/types/voice";
import { NextRequest, NextResponse } from "next/server";

import { randomUUID } from "crypto";
import { mkdir, writeFile } from "fs/promises";
import path from "path";

const interviewerVoice: Voice = "nova";
const intervieweeVoice: Voice = "ballad";
const interviewerInput = "Why the Netherlands?";
const intervieweeInput = `We chose the Netherlands...
because it has a strong combination of demand,
structure,
and fragmentation.`;
const interviewerInstruction = `You are the interviewer in a realistic interview-style podcast.

Voice direction:
- Calm, professional, slightly curious
- Ask the question naturally
- Keep the delivery clear and moderate
- Do not sound robotic
- Add a slight pause at the end of the question`;

const intervieweeInstruction = `You are the founder in a realistic interview-style podcast.

Voice direction:
- Confident, clear, thoughtful
- Answer in a structured but conversational way
- Keep the pacing moderate
- Do not rush
- Add slight pauses between key ideas
- Sound natural, not robotic`;

export async function POST(req: NextRequest) {
  try {
    // get AI client
    const aiClient = getAIClient();

    // Generate interviewer audio
    const interviewerAudioResponse = await aiClient.audio.speech.create({
      model: process.env.OPENAI_TTS_MODEL || "gpt-4o-mini-tts",
      voice: interviewerVoice,
      input: interviewerInput,
      instructions: interviewerInstruction,
      response_format: "mp3",
    });

    const interviewerAudioBuffer = Buffer.from(
      await interviewerAudioResponse.arrayBuffer(),
    );

    // Generate interviewee audio
    const intervieweeAudioResponse = await aiClient.audio.speech.create({
      model: process.env.OPENAI_TTS_MODEL || "gpt-4o-mini-tts",
      voice: intervieweeVoice,
      input: intervieweeInput,
      instructions: intervieweeInstruction,
      response_format: "mp3",
    });

    const intervieweeAudioBuffer = Buffer.from(
      await intervieweeAudioResponse.arrayBuffer(),
    );

    // Merge both MP3 buffers into a single downloadable MP3 file.
    // This works for a first local test because both files are generated by the same model and format.
    const mergedAudioBuffer = Buffer.concat([
      interviewerAudioBuffer,
      intervieweeAudioBuffer,
    ]);

    const outputDir = path.join(process.cwd(), "public", "generated");
    await mkdir(outputDir, { recursive: true });

    const fileName = `askfund-interview-${randomUUID()}.mp3`;
    const filePath = path.join(outputDir, fileName);

    await writeFile(filePath, mergedAudioBuffer);

    const downloadLink = `/generated/${fileName}`;

    return NextResponse.json({
      success: true,
      message: "Audio generated successfully",
      data: {
        downloadLink,
      },
    });

  } catch (error) {
    console.error("POST /api/audio/interview-mode error:", error);
    return NextResponse.json(
      {
        success: false,
        error: `Unexpected error occurred while creating new audio`,
      },
      { status: 500 },
    );
  }
}
